services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_ROOT_PASSWORD=example'
      - 'MYSQL_DATABASE=loan-calculator'
      - 'MYSQL_USER=example'
      - 'MYSQL_PASSWORD=example'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: